parameters:
    ongr_category_manager.connection.mapping:
        node:
            mapping:
                properties:
                    id:
                        type: string
                        index: not_analyzed
                    rootId:
                        type: string
                        index: not_analyzed
                    path:
                        type: string
                        analyzer: default
                        index_analyzer: default
                        search_analyzer: default

    ongr_category_manager.node_model_connection.settings:
        index:
            number_of_replicas: 1
            number_of_shards: 1
            refresh_interval: -1
        analysis:
            analyzer:
                default:
                    type: snowball
                    language: German2
                    stopwords: "der,die,das,mit,und,für"
services:
    ongr_category_manager.elastic_search_driver:
        class: ONGR\DDALBundle\ElasticSearch\ElasticSearchDriver
        arguments:
            - { host: %database.elastic_search.host%, port: %database.elastic_search.port%, throwCustomExceptions: 1}
            -
              index: %ongr_category_manager.connection.index_name%
              host: %ongr_category_manager.connection.host%
              port: %ongr_category_manager.connection.port%
              map: %ongr_category_manager.connection.mapping%
              settings: %ongr_category_manager.node_model_connection.settings%
              dynamicSettings: %database.elastic_search.dynamic_settings%
              scroll_settings: %database.elastic_search.scroll_settings%
        tags:
            - { name: ongr_ddal.driver, driver: category_manager }
        calls:
            - [setDisableFlushCall, [1]]
            - [setRefreshOnFlush, [1]]
