parameters:
    ongr_category_manager.model_map: ONGRElasticSearchBundle

    ongr_elasticsearch:
        connections:
            default:
                hosts:
                    - { host: %database.elastic_search.host% }
                index_name: %ongr_category_manager.connection.index_name%
                settings: %ongr_category_manager.node_model_connection.settings%
        managers:
            default:
                connection: default
                mappings: %ongr_category_manager.connection.mapping%

