parameters:
    ongr_category_manager.model_map:
        NodeModel.class: ONGRElasticSearchBundle

    ongr_elasticsearch:
        connections:
            default:
                hosts:
                    - { host: %database.elastic_search.host% }
                index_name: %ongr_category_manager.connection.index_name%
                settings:
                    refresh_interval: -1
                    number_of_replicas: 0
        managers:
            default:
                connection: default
                mappings:
                    - %ongr_category_manager.model_map%
