ongr_category_manager_home:
    pattern: /
    defaults: { _controller: ONGRCategoryManagerBundle:CategoryManager:list }

ongr_category_manager_list:
    pattern: /list
    defaults: { _controller: ONGRCategoryManagerBundle:CategoryManager:list }

ongr_category_manager_save:
    pattern: /save/{categoryId}
    methods: [POST]
    defaults: { _controller: ONGRCategoryManagerBundle:CategoryManager:save }
    requirements:
        categoryId:  '[^/]*'
    options:
        expose: true

ongr_category_manager_remove:
    pattern: /remove/{categoryId}
    defaults: { _controller: ONGRCategoryManagerBundle:CategoryManager:remove }
    options:
        expose: true

ongr_category_manager_plain_tree:
    pattern: /tree/plain
    methods: [POST]
    defaults: { _controller: ONGRCategoryManagerBundle:CategoryManager:plainTree }
    options:
        expose: true

ongr_category_manager_tree:
    pattern: /tree
    methods: [POST]
    defaults: { _controller: ONGRCategoryManagerBundle:CategoryManager:tree }
    options:
        expose: true

ongr_category_manager_move:
    pattern: /move
    methods: [POST]
    defaults: { _controller: ONGRCategoryManagerBundle:CategoryManager:move}
    options:
        expose: true

ongr_category_manager_matches:
    pattern: /matches
    methods: [POST]
    defaults: { _controller: ONGRCategoryManagerBundle:MatchManager:matches}
    options:
        expose: true

ongr_category_manager_match:
    pattern: /match
    methods: [POST]
    defaults: { _controller: ONGRCategoryManagerBundle:MatchManager:match}
    options:
        expose: true

ongr_category_manager_remove_match:
    pattern: /remove-match
    methods: [POST]
    defaults: { _controller: ONGRCategoryManagerBundle:MatchManager:removeMatch}
    options:
        expose: true

ongr_category_manager_suggestions:
    pattern: /suggestions
    methods: [POST]
    defaults: { _controller: ONGRCategoryManagerBundle:Suggestions:list}
    options:
        expose: true
