parameters:
    ongr_category_manager.category_manager.class: ONGR\CategoryManagerBundle\Service\CategoryManager
    ongr_category_manager.transfer_manager.class: ONGR\CategoryManagerBundle\Service\TransferManager
    ongr_category_manager.suggestions_manager.class: ONGR\CategoryManagerBundle\Service\SuggestionsManager
    ongr_category_manager.match_manager.class: ONGR\CategoryManagerBundle\Service\MatchManager
    ongr_category_manager.category_provider.class: ONGR\CategoryManagerBundle\Provider\CategoryProvider
    ongr_category_manager.iterator.csv.class: ONGR\CategoryManagerBundle\Iterator\CsvCategoryIterator
    ongr_category_manager.writer.mysql.class: ONGR\CategoryManagerBundle\Writer\MySqlCategoryWriter
    ongr_category_manager.listener.category_update.class: ONGR\CategoryManagerBundle\EventListener\CategoryUpdateListener
    ongr_category_manager.listener.category_remove.class: ONGR\CategoryManagerBundle\EventListener\CategoryRemoveListener
    ongr_category_manager.sync.doctrine.provider.class: ONGR\ConnectionsBundle\Doctrine\Provider\Provider
    ongr_category_manager.modifier.node.class: ONGR\CategoryManagerBundle\Modifier\NodeModifier

services:
    ongr_category_manager.category_manager:
        class: %ongr_category_manager.category_manager.class%
        arguments:
            - @ongr_category_manager.entity_manager

    ongr_category_manager.transfer_manager:
        class: %ongr_category_manager.transfer_manager.class%

    ongr_category_manager.match_manager:
        class: %ongr_category_manager.match_manager.class%
        arguments:
            - @ongr_category_manager.entity_manager

    ongr_category_manager.suggestions_manager:
        class: %ongr_category_manager.suggestions_manager.class%
        arguments:
            - @es.manager.default
            - @ongr_category_manager.entity_manager

    ongr_category_manager.provider.csv:
        class: %ongr_category_manager.category_provider.class%
        arguments:
            - %ongr_category_manager.iterator.csv.class%
        calls:
            - [ setContainer, [@service_container] ]
        tags:
            - { name: ongr_category_manager.provider, id: csv }

    ongr_category_manager.writer.mysql:
        class: %ongr_category_manager.writer.mysql.class%
        arguments:
            - @ongr_category_manager.entity_manager
        tags:
            - { name: ongr_category_manager.writer, id: mysql}

    ongr_category_manager.listener.category_update:
        class: %ongr_category_manager.listener.category_update.class%
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    ongr_category_manager.listener.category_remove:
        class: %ongr_category_manager.listener.category_remove.class%
        tags:
            - { name: doctrine.event_subscriber }

    ongr_category_manager.modifier.node:
        class: %ongr_category_manager.modifier.node.class%
        arguments:
            - @ongr_category_manager.entity_manager
        tags:
            - { name: fox_connections.doctrine.modifier, type: node }

    ongr_category_manager.sync.doctrine.provider:
        class: %ongr_category_manager.sync.doctrine.provider.class%
        arguments:
            - @es.manager.default
            - @ongr_category_manager.entity_manager
            - 'ONGRCategoryManagerBundle:Category'
        tags:
            - { name: ongr_connections.doctrine.provider, type: node }
