parameters:
    fox_category_manager.category_manager.class: Fox\CategoryManagerBundle\Service\CategoryManager
    fox_category_manager.transfer_manager.class: Fox\CategoryManagerBundle\Service\TransferManager
    fox_category_manager.suggestions_manager.class: Fox\CategoryManagerBundle\Service\SuggestionsManager
    fox_category_manager.match_manager.class: Fox\CategoryManagerBundle\Service\MatchManager
    fox_category_manager.category_provider.class: Fox\CategoryManagerBundle\Provider\CategoryProvider
    fox_category_manager.iterator.csv.class: Fox\CategoryManagerBundle\Iterator\CsvCategoryIterator
    fox_category_manager.writer.mysql.class: Fox\CategoryManagerBundle\Writer\MySqlCategoryWriter
    fox_category_manager.listener.category_update.class: Fox\CategoryManagerBundle\EventListener\CategoryUpdateListener
    fox_category_manager.listener.category_remove.class: Fox\CategoryManagerBundle\EventListener\CategoryRemoveListener
    fox_category_manager.sync.doctrine.provider.class: Fox\ConnectionsBundle\Doctrine\Provider\Provider
    fox_category_manager.modifier.node.class: Fox\CategoryManagerBundle\Modifier\NodeModifier

services:
    fox_category_manager.category_manager:
        class: %fox_category_manager.category_manager.class%
        arguments:
            - @fox_category_manager.entity_manager

    fox_category_manager.transfer_manager:
        class: %fox_category_manager.transfer_manager.class%

    fox_category_manager.match_manager:
        class: %fox_category_manager.match_manager.class%
        arguments:
            - @fox_category_manager.entity_manager

    fox_category_manager.suggestions_manager:
        class: %fox_category_manager.suggestions_manager.class%
        arguments:
            - @fox_ddal.session.category_manager.nodemodel
            - @fox_category_manager.entity_manager

    fox_category_manager.provider.csv:
        class: %fox_category_manager.category_provider.class%
        arguments:
            - %fox_category_manager.iterator.csv.class%
        calls:
            - [ setContainer, [@service_container] ]
        tags:
            - { name: fox_category_manager.provider, id: csv }

    fox_category_manager.writer.mysql:
        class: %fox_category_manager.writer.mysql.class%
        arguments:
            - @fox_category_manager.entity_manager
        tags:
            - { name: fox_category_manager.writer, id: mysql}

    fox_category_manager.listener.category_update:
        class: %fox_category_manager.listener.category_update.class%
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    fox_category_manager.listener.category_remove:
        class: %fox_category_manager.listener.category_remove.class%
        tags:
            - { name: doctrine.event_subscriber }

    fox_category_manager.modifier.node:
        class: %fox_category_manager.modifier.node.class%
        arguments:
            - @fox_category_manager.entity_manager
        tags:
            - { name: fox_connections.doctrine.modifier, type: node }

    fox_category_manager.sync.job_manager:
        class: %fox_connections.sync.job_manager.class%
        arguments:
            - @fox_category_manager.entity_manager
            - 'FoxConnectionsBundle:'
        calls:
            - [setLogger, [@fox_sync_jobs_logger]]

    fox_category_manager.sync.data_sync_service:
        class: %fox_connections.data_sync_service.class%
        arguments:
            - @fox_ddal.session.category_manager
            - @fox_connections.url_invalidator_service
        calls:
            - [setLogger, [@fox_sync_jobs_logger]]
            - [setEnableUpdateApi, [%fox_connections.data_sync_service.enableUpdateApi%]]
            - [setDataCollector, [@fox_connections.doctrine_data_collector]]

    fox_category_manager.sync.doctrine.provider:
        class: %fox_category_manager.sync.doctrine.provider.class%
        arguments:
            - @fox_ddal.session.category_manager.nodemodel
            - @fox_category_manager.entity_manager
            - 'FoxCategoryManagerBundle:Category'
        tags:
            - { name: fox_connections.doctrine.provider, type: node }

    fox_connections.sync_manager.category_manager:
        class: %fox_connections.sync.sync_manager.class%
        arguments:
            - @fox_category_manager.sync.data_sync_service
            - @fox_category_manager.sync.job_manager
