language: php
php:
  - 5.5
env:
  - SYMFONY="2.5.*"
services:
  - elasticsearch
install:
  - composer require --no-update symfony/symfony:${SYMFONY}
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - echo `which hhvm`
  - composer -V
  - echo `which composer`
  - /usr/bin/hhvm `which composer` update --prefer-dist -vvv --profile
script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs -p --standard=$TRAVIS_BUILD_DIR/vendor/ongr/ongr-strict-standard/ONGR --ignore=vendor/,Tests/app/ --extensions=php  ./
